In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
%cd / content/gdrive/MyDrive/cs394n_project/CS394N
! pip3 install -r requirements.txt

In [ ]:
# Update path for custom module support in Google Colab
import sys
sys.path.append('/content/gdrive/MyDrive/cs394n_project/CS394N/src')

In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np

from torch.utils.data import DataLoader

from torchvision import transforms
from torchvision.datasets import CIFAR10, FashionMNIST

#from tqdm.autonotebook import tqdm, trange

from utils.nets import *
from utils.model_tools import *
from utils.dataset_tools import split_training_data
from utils.feature_extractor import *
from utils.cosine_similarity import *
from utils.gen_dataset import *

In [2]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [18]:
model_dir = './models/'
log_dir = './logs/'
data_dir = './data/'

model_selection = 'linear' # linear | cnn | vgg
dataset_selection = 'fashionmnist' # cifar10 | fashionmnist

ckpt_file = model_dir + model_selection + '_' + dataset_selection + '_' + 'holdout_[8, 9].pt'
gen_dataset_path = data_dir + "gen-" + dataset_selection + '.csv'

holdout_classes = [8, 9]
new_class = 8

batch_size = 32
num_classes = 9

#### Hyperparameters

In [13]:
num_epochs = 15

initial_learning_rate = 0.001
final_learning_rate = 0.0001

# initial_lr * decay_rate^num_epochs = final_lr
decay_rate = (final_learning_rate/initial_learning_rate)**(1/num_epochs)

loss_fn = torch.nn.CrossEntropyLoss()
#optimizer = torch.optim.Adam(model.parameters(), lr=initial_learning_rate)
#lr_scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer=optimizer, gamma=decay_rate)

# Data Preparation

In [14]:
if dataset_selection == 'fashionmnist':
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5), (0.5)),]) # Images are grayscale -> 1 channel
else:
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

In [15]:
if dataset_selection == 'cifar10':
    train_data = CIFAR10(root='./data', train=True, download=True, transform=transform)
    test_data = CIFAR10(root='./data', train=False, download=True, transform=transform)
elif dataset_selection == 'fashionmnist':
    train_data = FashionMNIST(root='./data', train=True, download=True, transform=transform)
    test_data = FashionMNIST(root='./data', train=False, download=True, transform=transform)

In [16]:
total_classes = len(np.unique(train_data.targets))

## FOL

In [8]:
if model_selection == 'linear':
    fol_model = add_output_nodes(ckpt_file, device, arch='linear')
    fol_model.input_layer.requires_grad_(False)
elif model_selection == 'cnn-demo':
    fol_model = add_output_nodes(ckpt_file, device, arch='cnn-demo')
    fol_model.conv1.requires_grad_(False)
    fol_model.conv2.requires_grad_(False)
    fol_model.fc1.requires_grad_(False)
elif model_selection == 'cnn':
    fol_model = add_output_nodes(ckpt_file, device, arch='cnn')
    fol_model.conv_block1.requires_grad_(False)
    fol_model.conv_block2.requires_grad_(False)
    fol_model.conv_block3.Conv5.requires_grad_(False)
    fol_model.conv_block3.Relu5.requires_grad_(False)
    fol_model.conv_block3.BN5.requires_grad_(False)
    
fol_model = fol_model.to(device)

In [12]:
fol_optimizer = torch.optim.Adam(fol_model.parameters(), lr=initial_learning_rate)
fol_lr_scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer=fol_optimizer, gamma=decay_rate)

In [ ]:
# just train on the new class
included_data, excluded_data = split_training_data(train_data, [new_class]) 
train_fol_loader = DataLoader(excluded_data, batch_size=batch_size, shuffle=True, num_workers=2)

# but test on the full 9 classes (old classes + new one, still excluding one)
included_data, excluded_data = split_training_data(test_data, [8])
test_fol_loader = DataLoader(included_data, batch_size=batch_size, shuffle=True, num_workers=2)

In [ ]:
model_file_fol = weight_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + 'fol' + '.pt'

recall_file_fol = log_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + 'fol' + '_recall.npy'
train_losses_file_fol = log_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + 'fol' + '_train_loss.txt'
test_losses_file_fol = log_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + 'fol' + '_test_loss.txt'

### Training Loop

In [ ]:
train_losses = []
test_losses = []
#t = trange(num_epochs)
t = range(num_epochs)
y_preds = []
y_actuals = []

for epoch in t:
    print(f"Epoch {epoch+1}\n-------------------------------")
    train_loss = train(train_fol_loader, fol_model, loss_fn, fol_optimizer, device)
    test_loss, y_pred, y_actual = test(test_fol_loader, fol_model, loss_fn, device, swap=True, swap_labels=[9,8])
    print('y_pred:', y_pred[:2])
    print('y_actual:', y_actual[:2])
    train_losses.append(train_loss)
    test_losses.append(test_loss)
    y_preds.append(y_pred)
    y_actuals.append(y_actual)
    
    fol_lr_scheduler.step()
    
torch.save(fol_model.state_dict(), model_file_fol)


recalls = get_recall_per_epoch(y_actuals, y_preds, num_classes)
np.save(recall_file_fol, recalls)

with open(train_losses_file_fol, 'w') as fp:
    for s in train_losses:
        fp.write("%s\n" % s)
        
with open(test_losses_file_fol, 'w') as fp:
    for x in test_losses:
        fp.write("%s\n" % x)

print("Done!")

# Ok I'm struggling with getting data loading correct for FOL but I'm not sure we even need it

## SWIL

In [ ]:
if model_selection == 'linear':
    swil_model = add_output_nodes(ckpt_file, arch='linear')
    swil_model.input_layer.requires_grad_(False)
elif model_selection == 'cnn-demo':
    swil_model = add_output_nodes(ckpt_file, arch='cnn-demo')
    swil_model.conv1.requires_grad_(False)
    swil_model.conv2.requires_grad_(False)
    swil_model.fc1.requires_grad_(False)
    
swil_model = swil_model.to(device)

In [ ]:
swil_optimizer = torch.optim.Adam(swil_model.parameters(), lr=initial_learning_rate)
lr_scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer=swil_optimizer, gamma=decay_rate)

In [ ]:
fmnist_classes = list(range(8)) + [9]

# might not need these
FMNIST_trainloader_gen = torch.utils.data.DataLoader(train_data, batch_size=batch_size,
                                          shuffle=True, num_workers=2)
FMNIST_testloader_gen = torch.utils.data.DataLoader(test_data, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

class_subsets, class_idxs, subset_size = generate_dls(train_data, fmnist_classes)

In [ ]:
with open(r'./data/fmnist_sim_scores_boot.txt', 'r') as fp:
    sim_scores = [float(i) for i in fp.readlines()]

sim_sum = sum(sim_scores)

sim_norms = [x/sim_sum for x in sim_scores]

boots_sample_size = 75
sim_sample_sizes = [27 if x < 0.2 else int(x * boots_sample_size*3.52) for x in sim_norms] + [75]

In [ ]:
from random import sample

sampled_idxs = []

for i in range(len(fmnist_classes)):
    idx_sample = sample(class_idxs[i].tolist(), sim_sample_sizes[i])
    sampled_idxs += idx_sample

swil_train_subset = torch.utils.data.Subset(train_data, sampled_idxs)

swil_train_dl = torch.utils.data.DataLoader(swil_train_subset, batch_size=1, shuffle=True, num_workers=2)

included_data, excluded_data = split_training_data(test_data, [8])
test_swil_loader = DataLoader(included_data, batch_size=batch_size, shuffle=True, num_workers=2)

### Training Loop

In [ ]:
weight_dir = './weights/'
model_file = weight_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + '_swil.pt'
recall_file = weight_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + '_swil_recall.npy'
train_losses_file = weight_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + '_swil_train_loss.txt'
test_losses_file = weight_dir + model_selection + '_' + dataset_selection + '_' + 'holdout' + '_' + '[8]' + 'swil_test_loss.txt'
train_losses = []
test_losses = []
#t = trange(num_epochs)
t = range(num_epochs)
y_preds = []
y_actuals = []

for epoch in t:
    print(f"Epoch {epoch+1}\n-------------------------------")
    train_loss = train(swil_train_dl, swil_model, loss_fn, swil_optimizer, device, swap=True, swap_labels=[9,8])
    test_loss, y_pred, y_actual = test(test_swil_loader, swil_model, loss_fn, device, swap=True, swap_labels=[9,8])
    train_losses.append(train_loss)
    test_losses.append(test_loss)
    y_preds.append(y_pred)
    y_actuals.append(y_actual)
    
    #t.set_description(f"Epoch {epoch} train loss: {epoch_loss_train[-1]:.3f}")
    lr_scheduler.step()
    
torch.save(swil_model.state_dict(), model_file)

recalls = get_recall_per_epoch(y_actuals, y_preds, 9)
np.save(recall_file, recalls)

with open(train_losses_file, 'w') as fp:
    for s in train_losses:
        fp.write("%s\n" % s)
        
with open(test_losses_file, 'w') as fp:
    for x in test_losses:
        fp.write("%s\n" % x)

print("Done!")

## G-SWIL

In [19]:
if model_selection == 'linear':
    gswil_model = add_output_nodes(ckpt_file, arch='linear', device=device)
    gswil_model.input_layer.requires_grad_(False)
elif model_selection == 'cnn-demo':
    gswil_model = add_output_nodes(ckpt_file, arch='cnn-demo', device=device)
    gswil_model.conv1.requires_grad_(False)
    gswil_model.conv2.requires_grad_(False)
    gswil_model.fc1.requires_grad_(False)
elif model_selection == 'cnn':
    gswil_model = add_output_nodes(ckpt_file, arch='cnn', device=device)
    gswil_model.conv_block1.requires_grad_(False)
    gswil_model.conv_block2.requires_grad_(False)
    gswil_model.conv_block3.Conv5.requires_grad_(False)
    gswil_model.conv_block3.Relu5.requires_grad_(False)
    gswil_model.conv_block3.BN5.requires_grad_(False)
    
gswil_model = gswil_model.to(device)

input_size 784
num_outputs 9


In [20]:
gswil_optimizer = torch.optim.Adam(gswil_model.parameters(), lr=initial_learning_rate)
gswil_scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer=gswil_optimizer, gamma=decay_rate)

In [21]:
# this will be different for cnn 

with open(r'./data/fmnist_sim_scores_boot.txt', 'r') as fp:
    sim_scores = [float(i) for i in fp.readlines()]

sim_sum = sum(sim_scores)

sim_norms = [x/sim_sum for x in sim_scores]

boots_sample_size = 75
sim_sample_sizes = [27 if x < 0.2 else int(x * boots_sample_size*3.52) for x in sim_norms] + [75]

In [113]:
from torch.utils.data import Dataset
import os
from PIL import Image

import pandas as pd

class GenDataset(Dataset):
    """All-purpose (FMNIST or CIFAR10) generated dataset."""

    def __init__(self, csv_file, root_dir, data_name='img', class_name='label', transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.landmarks_frame = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform
        self.files = self.landmarks_frame[data_name].values
        self.data = self._load_data()
        self.targets = self.landmarks_frame[class_name].values
        
    def _load_data(self):
        data = np.empty((len(self.files),255,255,3))
        for f in self.files:
            img_name = os.path.join(self.root_dir, f)
            image = np.asarray(Image.open(img_name))
            np.append(data, image)
        
        return data

    def __len__(self):
        return len(self.landmarks_frame)

    def __getitem__(self, idx):
        #if torch.is_tensor(idx):
        #    idx = idx.tolist()
        
        img, target = self.data[idx], self.targets[idx]
        
        # this is done for FMNIST, need for CIFAR10?
        #img = Image.fromarray((img[:,:,:3] * [0.2989, 0.5870, 0.1140]).sum(axis=2), mode="L")

        if self.transform is not None:
            img = self.transform(img)
        
        return torch.tensor(img), torch.tensor(target)
    

In [114]:
# mostly the same here, but will differ in the bottom few lines

from random import sample

sampled_idxs = []

gfmnist_dataset = GenDataset(csv_file=gen_dataset_path,
                                    root_dir=data_dir + 'GFashionMNIST')

print(gfmnist_dataset.targets)
print(gfmnist_dataset.data.shape)

fmnist_classes = list(range(8)) # just get old classes from generated data

class_subsets, old_class_idxs, subset_size = generate_dls(gfmnist_dataset, fmnist_classes)
# where subset_size?

for i in range(len(fmnist_classes)):
    idx_sample = sample(old_class_idxs[i].tolist(), 1)#sim_sample_sizes[i])
    sampled_idxs += idx_sample
    
gswil_train_old_subset = torch.utils.data.Subset(gfmnist_dataset, sampled_idxs)

gswil_new_subset, new_class_idx, subset_size = generate_dls(train_data, [9])
new_class_idx_sample = sample(new_class_idx[0].tolist(), 1)#sim_sample_sizes[-1])
gswil_train_new_subset = torch.utils.data.Subset(train_data, new_class_idx_sample)

gswil_combined_subset = torch.utils.data.ConcatDataset([gswil_train_old_subset, gswil_train_new_subset])
gswil_combined_subset_test = torch.utils.data.ConcatDataset([gfmnist_dataset, gswil_train_new_subset])

gswil_train_dl = torch.utils.data.DataLoader(gswil_combined_subset, batch_size=1, shuffle=True, num_workers=2)
gswil_train_dl_test = torch.utils.data.DataLoader(gswil_combined_subset_test, batch_size=1, shuffle=True, num_workers=2)

#included_data, excluded_data = split_training_data(test_data, [8])
#gswil_train_dl = DataLoader(included_data, batch_size=batch_size, shuffle=True, num_workers=2)

[8 0 1 7 4 6 2 3 5]
(9, 255, 255, 3)


In [116]:
def imshow(img):
    #img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(npimg) #np.transpose(npimg, (1, 2, 0)))
    plt.show()

for img, label in gswil_train_dl_test:
    #imshow(img)
    print(img.shape)
    print(label)
    #print(img, label)

torch.Size([1, 255, 255, 3])
tensor([8])
torch.Size([1, 255, 255, 3])
tensor([2])
torch.Size([1, 255, 255, 3])
tensor([4])
torch.Size([1, 255, 255, 3])
tensor([3])
torch.Size([1, 255, 255, 3])
tensor([6])
torch.Size([1, 255, 255, 3])
tensor([1])
torch.Size([1, 1, 28, 28])
tensor([9])
torch.Size([1, 255, 255, 3])
tensor([5])
torch.Size([1, 255, 255, 3])
tensor([0])
torch.Size([1, 255, 255, 3])
tensor([7])


### Training Loop

In [ ]:
# should be dataset-agnostic

weight_dir = './weights/'
model_file = weight_dir + model_selection + '_' + dataset_selection '_gswil.pt'
recall_file = weight_dir + model_selection + '_' + dataset_selection +  '_gswil_recall.npy'
train_losses_file = weight_dir + model_selection + '_' + dataset_selection + '_gswil_train_loss.txt'
test_losses_file = weight_dir + model_selection + '_' + dataset_selection + '_gswil_test_loss.txt'
accuracies_file = weight_dir + model_selection + '_' + dataset_selection + '_gswil_test_loss.txt'

train_losses = []
test_losses = []
accuracies = []
t = range(num_epochs)
y_preds = []
y_actuals = []

for epoch in t:
    print(f"Epoch {epoch+1}\n-------------------------------")
    train_loss = train(gswil_train_dl, swil_model, loss_fn, gswil_optimizer, device)
    test_loss, y_pred, y_actual, accuracy = test(test_swil_loader, gswil_model, loss_fn, device)
    train_losses.append(train_loss)
    test_losses.append(test_loss)
    accuracies.append(accuracy)
    y_preds.append(y_pred)
    y_actuals.append(y_actual)
    
    gswil_scheduler.step()
    
torch.save(swil_model.state_dict(), model_file)

recalls = get_recall_per_epoch(y_actuals, y_preds, 9)
np.save(recall_file, recalls)

with open(train_losses_file, 'w') as fp:
    for s in train_losses:
        fp.write("%s\n" % s)
        
with open(test_losses_file, 'w') as fp:
    for x in test_losses:
        fp.write("%s\n" % x)
        
with open(accuracies_file, 'w') as fp:
    for x in accuracies:
        fp.write("%s\n" % x)

print("Done!")